rainbow_mock/rainbow_mock/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from django.views.generic import TemplateView

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/signup/', TemplateView.as_view(template_name='signup.html'), name='signup'),
]


urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

rainbow_mock/schedule/urls.py
from django.urls import path

from . import views

app_name = 'schedule'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('setting-schedule/', views.add, name="schedule_setting"),
    path('mail-test/', views.mail_test, name="mail_test"),
    path('private-schedule/', views.ScheduleView.as_view(), name="schedule_index"),
]

rainbow_mock/schedule/models.py
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser
from .validate import valid_gender
from .validate import valid_occupation


# Create your models here.
class Prof(models.Model):
    GENDER_SELECTION = ((0, '男性'), (1, '女性'))
    OCCUPATION_SELECTION = ((0, '会社員'), (1, '専業主婦'), (2, '学生'), (3, 'その他'))

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    nick_name = models.CharField(verbose_name='ニックネーム', max_length=100, default='jack/peter/mike/etc..')
    gender = models.CharField(verbose_name='性別', max_length=3, validators=[valid_gender], choices=GENDER_SELECTION)
    barth_date = models.DateTimeField(verbose_name='生年月日', null=True)
    occupation = models.CharField(
        verbose_name='職業', max_length=10, validators=[valid_occupation], choices=OCCUPATION_SELECTION
    )
    hobby = models.TextField(verbose_name='趣味', blank=True, null=True)
    has_child_num = models.IntegerField(verbose_name='子供の数')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Profile'

    def __str__(self):
        return self.user.username


class Children(models.Model):
    GENDER_SELECTION = ((0, '男性'), (1, '女性'))

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='子供の名前', max_length=100, null=True)
    gender = models.CharField(verbose_name='子供の性別', max_length=3, validators=[valid_gender], choices=GENDER_SELECTION)
    barth_date = models.DateTimeField(verbose_name='子供の生年月日', null=True)
    hobby = models.TextField(verbose_name='好きな遊び', blank=True, null=True)
    character = models.TextField(verbose_name='好きなキャラクター', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Children'

    def __str__(self):
        return self.user.username + ':' + self.name


class Partner(models.Model):
    OCCUPATION_SELECTION = ((0, '会社員'), (1, '専業主婦'), (2, '学生'), (3, 'その他'))

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='パートナーの名前', max_length=100, null=True)
    barth_date = models.DateTimeField(verbose_name='パートナーの生年月日', null=True)
    occupation = models.CharField(
        verbose_name='パートナーの職業', max_length=5, validators=[valid_occupation], choices=OCCUPATION_SELECTION
    )
    hobby = models.TextField(verbose_name='パートナーの趣味', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Partner'

    def __str__(self):
        return self.user.username + ':' + self.name


class Schedules(models.Model):
    SCHEDULE_SELECTION = ((0, '●'), (1, '▲'), (2, '×'))
    PERIOD_SELECTION = ((0, '午前'), (1, '正午'), (2, '午後'))

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    schedule_date = models.DateField(verbose_name='日付', default=timezone.now())
    status = models.IntegerField(verbose_name='状態', choices=SCHEDULE_SELECTION, default=1)
    period = models.IntegerField(verbose_name='時間帯', choices=PERIOD_SELECTION, default=0)

    def __show_period__(self):
        display_period = ''
        for p in self.PERIOD_SELECTION:
            if p[0] == self.period:
                display_period = p[1]
        return display_period

    class Meta:
        verbose_name_plural = 'Schedule'

    def __str__(self):
        return self.user.username + ':' + str(self.schedule_date) + ' ' + self.__show_period__()


class Friends(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', related_name='user', on_delete=models.PROTECT)
    friend = models.ForeignKey(
        CustomUser, verbose_name='友人', related_name='friend', on_delete=models.PROTECT, null=True
    )
    group = models.CharField(verbose_name='グループ', max_length=100)

    class Meta:
        verbose_name_plural = 'Friends'

    def __str__(self):
        return self.user.username

rainbow_mock/schedule/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Schedules


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください．'

        self.fields['name'].widget.attrs['class'] = 'form-control col-11'
        self.fields['name'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください．'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください．'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください．'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス; {1}\nメッセージ: \n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()


class ScheduleSettingForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Schedules
        fields = '__all__'


ScheduleSettingFormSet = forms.modelformset_factory(
    Schedules, form=ScheduleSettingForm, extra=0
)

rainbow_mock/schedule/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib import messages
from django.db import connection
from .forms import InquiryForm, ScheduleSettingFormSet
from .models import Schedules, Friends
import os
import logging

from django.urls import reverse_lazy

logger = logging.getLogger(__name__)

# Create your views here.


class IndexView(generic.TemplateView):
    template_name = "index.html"


class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('schedule:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました．')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


def add(request):
    formset = ScheduleSettingFormSet(request.POST or None, queryset=Schedules.objects.filter(user=request.user))
    if request.method == 'POST':
        formset.save()
        return redirect('schedule:index')

    context = {
        'formset': formset
    }

    return render(request, 'schedule_setting.html', context)


class ScheduleView(LoginRequiredMixin, generic.ListView):
    model = Schedules
    template_name = 'schedule_index.html'

    def _custom_sql(self):
        query = '''
          SELECT * 
          FROM schedule_schedules 
          WHERE user_id = {i} or user_id in (select friend_id from schedule_friends where user_id = {i})
        '''.format(i=self.request.user.id)

        with connection.cursor() as cursor:
            cursor.execute(
                query
            )
            row = cursor.fetchall()

        return row

    def get_queryset(self):
        schedules = Schedules.objects.distinct().filter(
            user=self.request.user
        ).select_related()
    #    '''.filter(
    #        schedule_date__gte=timezone.now()
    #    )'''
    #    '''
    #    schedules.union(
    #        Schedules.objects.distinct().filter(
    #            user_id__in=list(Friends.objects.filter(user=self.request.user).values_list('friend_id', flat=True))
    #        ).filter(
    #            schedule_date__gte=timezone.now()
    #        ).select_related()
    #    )
    #    '''

        # friend = list(Friends.objects.all().filter(user=self.request.user).values_list('friend_id', flat=True))
        # return self._custom_sql()
        return schedules

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['friend_list'] = Schedules.objects.distinct().filter(
            user_id__in=list(Friends.objects.filter(user=self.request.user).values_list('friend_id', flat=True))
        )
        '''.filter(
            schedule_date__gte=timezone.now()
        )'''
        return context

from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string


def mail_test(request):
    """題名"""
    subject = "題名"
    """本文"""
    message = "本文です\nこんにちは。メールを送信しました"
    """送信元メールアドレス"""
    from_email = "{}".format(os.environ.get('FROM_EMAIL'))
    """宛先メールアドレス"""
    recipient_list = [
        "{}".format(os.environ.get('FROM_EMAIL'))
    ]

    context = {
        'mail_url': '{}'.format(os.environ.get('URL'))
    }
    msg_html = render_to_string('email_templates.html', context)
    send_mail(subject, message, from_email, recipient_list, html_message=msg_html,)
    return HttpResponse('<h1>email send complete.</h1>')

rainbow_mock/schedule/templates/base.html
{% load static %}

<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block title%}{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

        <!-- My style -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'schedule:index' %}">SCHEDULE</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item {% block active_inquiry %}{% endblock %}">
                                <a class="nav-link" href="{% url 'schedule:inquiry'%}">INQUIRY</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                            {% else %}
                            <li class="nav-item {% block action_signup %}{% endblock %}">
                                <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                            </li>
                            <li class="nav-item {% block active_login %}{% endblock %}">
                                <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {% block header %}
            <header class="masthead text-center text-white">
                <div class="masthead-content">
                    <div class="container">
                        <h1 class="masthead-heading mb-0">Private Schedule</h1>
                        <h2 class="masthead-subheading mb-0">スケジュール共有サービス</h2>
                        <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
                    </div>
                </div>
                <div class="bg-circle-1 bg-circle"></div>
                <div class="bg-circle-2 bg-circle"></div>
                <div class="bg-circle-3 bg-circle"></div>
                <div class="bg-circle-4 bg-circle"></div>
            </header>
            {% endblock %}

            {% if messages %}
            <div class="containers">
                <div class="row">
                    <div class="my-div-style w-100">
                        <ul class="messages" style="list-style: none;">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            {% endif %}

            {% block contents %}{% endblock %}

            <!-- Footer -->
            <footer class="py-5 bg-black">
                <div class="container">
                    <p class="m-0 text-center text-white small">Copy right &copy;Schedule 2019</p>
                </div>
                <!-- /.container -->
            </footer>

            <!-- Bootstrap core JavaScript -->
	    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
            <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        </div>
    </body>
</html>

rainbow_mock/schedule/templates/email_templates.html
<header class="masthead text-center text-white">
    <h1 class="masthead-heading mb-0">Private Schedule</h1>
</header>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{{mail_url}}static/img/01.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4"><a href='{{mail_url}}index.html'>Web Schedule</a></h2>
                    <p>Web上で共有できるスケジュール</p>
                </div>
            </div>
        </div>
    </div>
</section>

rainbow_mock/schedule/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Web上でママ・パパ友とスケジュールを共有できるサービス | Private Schedule{% endblock %}

{% block header %}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Private Schedule</h1>
            <h2 class="masthead-subheading mb-0">友人とのスケジュールマッチング</h2>
	    <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4"><a href="{% url 'schedule:schedule_index' %}">Web Schedule</a></h2>
                    <p>Web上で共有できるスケジュール</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4"><a href="{% url 'schedule:schedule_setting' %}">Save Your Schedule</a></h2>
                    <p>あなたのスケジュールを更新</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Membership System</h2>
                    <p>会員制のWebスケジューリングサービス</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

rainbow_mock/schedule/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Schedule {% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

rainbow_mock/schedule/templates/schedule_setting.html
{% extends 'base.html' %}

{% block title %}スケジュール更新 | Private Schedule {% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                <div class="form-group row">
                    <table class="table">
                    {% for form in formset %}
                        <tr>
                            <td>{{ form.schedule_date }}</td>
                            <td>{{ form.period.label }}</td>
                            <td>{{ form.period }}</td>
                            <td>{{ form.status.label }}</td>
                            <td>{{ form.status }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
                {{ formset.management_form }}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">更新</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}